name: Check
on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, task: linuxX64Test}
          - {os: macos-latest, task: macosX64Test}
          - {os: windows-latest, task: mingwX64Test}
    name: Check on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s ${{ matrix.config.task }} jvmTest
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
