name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, task: publish}
          - {os: macos-latest, task: publishMacosX64PublicationToMavenRepository}
          - {os: windows-latest, task: publishMingwX64PublicationToMavenRepository}
    name: Publish for ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s ${{ matrix.config.task }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g
